package:
  name: jom
  version: 1.0.16

build:
  skip:
    - [unix]

source:                                                              [win]
  fn: jom_1_0_16.zip                                                 [win]
  url: http://download.qt.io/official_releases/jom/jom_1_0_16.zip    [win]

test:
  commands:
    - jom /H

about:
    home: https://wiki.qt.io/Jom
    license: GPL
    summary: jom is a clone of nmake to support the execution of multiple independent commands in parallel.
