package:
  name: meld-plugin
  version: "0.1.2"


source:
  git_url: https://github.com/maccallumlab/meld-openmm-plugin.git
  git_rev: v0.1.2

build:
  skip: True  # [not linux]
    
requirements:
  build:
    - openmm-dev
    - cmake
    - python
    - swig
    - eigen3

  run:
    - python
    - openmm-dev

test:
  imports:
    - meldplugin
