package:
  name: meld-plugin
  version: "0.1.1"


source:
  git_url: https://github.com/maccallumlab/meld-openmm-plugin.git
  git_rev: v0.1.1

requirements:
  build:
    skip:
      [not linux]
    - openmm-dev
    - cmake
    - python
    - swig ==3.0.7
    - eigen3

  run:
    - python
    - openmm-dev
