# created with: conda skeleton pypi pystallone
package:
  name: pystallone
  version: !!str 1.0.0b6

source:
  fn: pystallone-1.0.0b6.tar.gz
  url: https://pypi.python.org/packages/source/p/pystallone/pystallone-1.0.0b6.tar.gz
  md5: 8b15d6a593b3ce99d3528e6f10cc47ef 

requirements:
  build:
    - python
    - setuptools
    - jpype1 >=0.5.6
    - numpy >=1.6.0

  run:
    - python
    - jpype1 >=0.5.6
    - numpy >=1.6.0

test:
  imports:
    - pystallone

about:
  home: http://bitbucket.org/cmb-fu/stallone
  license:  BSD License
  summary: 'Python binding for Stallone java library'

