package:
  name: cclib
  version: "1.3.1"

source:
  git_url: https://github.com/cclib/cclib.git
  git_tag: v1.3.1

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cclib = cclib:main
    #
    # Would create an entry point called cclib that calls cclib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - cclib
    - cclib.bridge
    - cclib.method
    - cclib.parser
    - cclib.progress

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://cclib.github.io/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'cclib: parsers and algorithms for computational chemistry'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
