package:
  name: deepchem
  version: "1.2.0"

source:
    git_url: https://github.com/deepchem/deepchem.git
    git_tag: 1.2.0

build:
  number: 0
  skip: True  # [osx or win or py3k]


requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pbr

  run:
    - pandas
    - scikit-learn
    - networkx
    - tensorflow >=1.1.0
    - py-xgboost
    - keras
    - rdkit
    - mdtraj
    - pdbfixer
    - joblib
    - h5py
    - dill

test:

  imports:
    - deepchem


about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  summary: 'Deep-learning models for Drug Discovery and Quantum Chemistry '
