package:
  name: parse
  version: !!str 1.6.6

source:
  fn: parse-1.6.6.tar.gz
  url: https://pypi.python.org/packages/source/p/parse/parse-1.6.6.tar.gz
  md5: 11bc8c60a30fe52db4ac9a827653d0ca
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - parse = parse:main
    #
    # Would create an entry point called parse that calls parse.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - parse

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/r1chardj0n3s/parse
  license: BSD License
  summary: 'parse() is the opposite of format()'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
