package:
  name: propertyestimator
  version: 0.0.7

source:
  git_url: https://github.com/openforcefield/propertyestimator.git
  git_tag: 0.0.7

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]

extra:
  #force_upload: True
  upload: main # Upload to anaconda with the "main" label.

requirements:
  build:
    - python
    - pip
    
    # For building sphinx docs
    - sphinx
    - sphinx_rtd_theme
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - testpath ==0.3.1

      # Standard dependencies
    - openforcefield ==0.4.0
    - smirnoff99frosst
    - numpy
    - pandas
    - openmm
    - pint
    - packmol
    - pymbar
    - mdtraj
    - dask >=2.6.0
    - distributed >=2.6.0
    - dask-jobqueue >=0.7.0
    - tornado <6
    - coverage >=4.4
    - uncertainties
    - openmmtools
    - yank >=0.24.1
    - pyyaml
    - requests
    - requests-mock
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.    


  run:
    - python
    - pip

    # Testing and development
    - pytest
    - pytest-cov
    - codecov

      # Commercial
    - openeye-toolkits

      # Standard dependencies
    - openforcefield ==0.4.0
    - smirnoff99frosst
    - numpy
    - pandas
    - openmm
    - pint
    - packmol
    - pymbar
    - mdtraj
    - dask >=2.6.0
    - distributed >=2.6.0
    - dask-jobqueue >=0.7.0
    - tornado
    - coverage >=4.4
    - uncertainties
    - openmmtools
    - yank >=0.24.1
    - pyyaml
    - requests
    - requests-mock
  
about:
  home: https://github.com/openforcefield/propertyestimator
  license: MIT
  license_file: LICENSE
  description: Property estimation toolkit from the Open Forcefield Consortium.
