package:
  name: autograd
  version: "1.1.4"

source:
  fn: autograd-1.1.4.tar.gz
  url: https://pypi.python.org/packages/c7/8e/a12c9b3b2bb21554d8de6caa2a3761497ff9015b7fa0df87652cf194550a/autograd-1.1.4.tar.gz
  md5: 06b9cc3c3a884769d90390b3ae14cca7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - autograd = autograd:main
    #
    # Would create an entry point called autograd that calls autograd.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - future
    - scipy

  run:
    - python
    - numpy x.x
    - future
    - scipy

test:
  # Python imports
  imports:
    - autograd
    - autograd.numpy
    - autograd.scipy
    - autograd.scipy.stats

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/HIPS/autograd
  license: MIT License
  summary: 'Efficiently computes derivatives of numpy code.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
