package:
  name: omnia
  version: 1.0


requirements:
  build:
    - python # necessary to ensure packages are built for each Python version
    - numpy # necessary to ensure packages are built for each Python version
  run:
    - python # necessary to ensure packages are built for each Python version
    - numpy # necessary to ensure packages are built for each Python version
    - openmm
    - mdtraj
    - pymbar
    - pdbfixer
    - msmbuilder
    - nose  # Needed to test everything

about:
  home: http://omnia.md
  license: GPL
  summary: Metapackage for the omnia.md biophysical simulation consortium.
