package:
  name: omnia
  version: 0.1


requirements:
  build: # needed to trigger automatic builds of omnia packges and dependencies
    - scripttest # omitted from mdtraj recipe, but required to run
    - openmm
    - mdtraj
    - pymbar
    - pdbfixer
    - msmbuilder
    - nose  # Needed to test everything
  run:
    - openmm
    - mdtraj
    - pymbar
    - pdbfixer
    - msmbuilder
    - nose  # Needed to test everything

about:
  home: http://omnia.md
  license: GPL
  summary: Metapackage for the omnia.md biophysical simulation consortium.
