{% set version = "3.2" %}

package:
    name: mpich
    version: {{ version }}

source:
    fn: mpich-{{ version }}.tar.gz
    url: http://www.mpich.org/static/downloads/{{ version }}/mpich-{{ version }}.tar.gz
    sha256: 0778679a6b693d7b7caff37ff9d2856dc2bfc51318bf8373859bfa74253da3dc

build:
    number: 4
    skip: True  # [win]

requirements:
    build:
        - gcc  # [not win]
        # - toolchain
    run:
        - libgcc  # [linux]
        - libgfortran  # [osx]

test:
    requires:
        - gcc  # [not win]
    files:
        - tests/helloworld.c
        - tests/helloworld.cxx
        - tests/helloworld.f
        - tests/helloworld.f90

extra:
    omnia-md-recipe-maintainer:
      - lnaden # Note: Not author of the recipe or source code
    recipe-maintainers:
        - astrofrog
        - bekozi
        - dalcinl
        - minrk
        - msarahan
        - ocefpaf
    copyright:
        - This repo is a clone of the conda-forge feedstock (without `commands` tests)
        - The about section was moved to extra to avoid bug in conda-build
        - Toolchain was commented out
    home: http://www.mpich.org/
    license: MPICH
    license_file: COPYRIGHT
    license_family: Other
    summary: 'A high performance widely portable implementation of the MPI standard.'
    description: |
      MPICH is a high performance and widely portable implementation of the
      Message Passing Interface (MPI) standard.
    doc_url: http://www.mpich.org/documentation/guides
    dev_url: https://wiki.mpich.org/mpich/index.php/Main_Page