package:
  name: parmed
  version: !!str 2.0beta1

source:
  fn: ParmEd-2.0-beta1.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/2.0beta1.tar.gz
  md5: 51ecb3d781fda3e13afc00f3d85ebb8e

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
