package:
  name: parmed
  version: !!str 2.0beta2

source:
  fn: ParmEd-2.0-beta2.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/v2.0-beta2.tar.gz
  md5: add3605f05da0a90dfbbfb080001a710

build:
  number: 2

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
