package:
  name: parmed
  version: !!str 2.0beta3

source:
  fn: ParmEd-2.0-beta3.tar.gz
  url: https://github.com/ParmEd/ParmEd/archive/v2.0-beta3.tar.gz
  md5: 62df64e824f691cbfc46c746701e04bf

build:
  number: 3

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - openmm

about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
