package:
  name: pybtex-docutils
  version: !!str 0.2.1

source:
  url: https://pypi.python.org/packages/source/p/pybtex-docutils/pybtex-docutils-0.2.1.tar.gz
  md5: 7ae4b00562bd8881f582edf95009cc62
  fn: pybtex-docutils-0.2.1.tar.gz

build:
  preserve_egg_dir: True

requirements:
  build:
    - setuptools
    - python
    - pybtex
    - six

  run:
    - python
    - pybtex
    - six

about:
  home: https://pypi.python.org/pypi/pybtex-docutils
  license: MIT
