package:
  name: cvxopt
  version: 1.1.8

source:
  fn: cvxopt-1.1.8.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxopt/cvxopt-1.1.8.tar.gz
  md5: d4ff0a0e51aba93f838a70302a088eea

  patches:
    - win-setup.patch  [win]
    - 0001-setup.patch

build:
  # TODO: no mingwpy on py35+ yet
  skip: True  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - mingwpy    [win]
    - openblas

  run:
    - python
    - openblas   [not win]

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GNU GPL version 3
  summary: 'Convex optimization package'
