package:
  name: numdifftools
  version: !!str 0.7.7

source:
  fn: numdifftools-0.7.7.zip
  url: https://pypi.python.org/packages/source/N/Numdifftools/numdifftools-0.7.7.zip
  md5: 07bce309b22fccee4af499c85518e90b

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.4
    - scipy >=0.8
    - six
    - algopy

  run:
    - python
    - numpy >=1.4
    - scipy >=0.8
    - six
    - algopy

test:
  # Python imports
  imports:
    - numdifftools
  requires:
    - matplotlib

about:
  home: http://code.google.com/p/numdifftools/
  license:  BSD License
  summary: 'Solves automatic numerical differentiation problems in one or more variables.'
