package:
  name: lomap
  version: "0.0.0"

source:
  git_rev: 0.0.0
  git_url: https://github.com/nividic/Lomap.git

build:
  skip:
    - [py3k]

requirements:
  build:
    - python
    - setuptools
    - boost ==1.59
    - rdkit
    - matplotlib
    - pyqt
    - networkx >=1.11
    - graphviz
    - pygraphviz
    - pil

  run:
    - python
    - boost ==1.59
    - rdkit 
    - matplotlib
    - pyqt
    - networkx
    - graphviz
    - pygraphviz
    - pil


test:
  requires:
    - nose
  imports:
    - lomap
  commands:
    - which lomap
    - lomap -h

about:
  home: https://github.com/nividic/Lomap
  license: LGPL
  license_file: LICENCE.txt  
  summary: Alchemical free-energy calculations planner