package:
  name: parse_type
  version: !!str 0.3.4

source:
  fn: parse_type-0.3.4.tar.gz
  url: https://pypi.python.org/packages/source/p/parse_type/parse_type-0.3.4.tar.gz
  md5: 00ba70bc5ca67624207b0dfced01dc8a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - parse_type = parse_type:main
    #
    # Would create an entry point called parse_type that calls parse_type.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - parse >=1.6
    - six
    - enum34 # [not py34]

  run:
    - python
    - parse >=1.6
    - six
    - enum34 # [not py34]

test:
  # Python imports
  imports:
    - _paver_ext
    - parse_type

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jenisys/parse_type
  license: BSD License
  summary: 'Simplifies to build parse types based on the parse module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
