package:
  name: parse_type
  version: !!str 0.3.4

source:
  fn: parse_type-0.3.4.tar.gz
  url: https://pypi.python.org/packages/source/p/parse_type/parse_type-0.3.4.tar.gz
  md5: 00ba70bc5ca67624207b0dfced01dc8a

requirements:
  build:
    - python
    - setuptools
    - parse >=1.6
    - six
    - enum34 # [py27]

  run:
    - python
    - parse >=1.6
    - six
    - enum34 # [py27]

test:
  # Python imports
  imports:
    - _paver_ext
    - parse_type

about:
  home: https://github.com/jenisys/parse_type
  license: BSD License
  summary: 'Simplifies to build parse types based on the parse module'
