package:
  name: yank
  version: "0.25.2"

source:
    url: https://github.com/choderalab/yank/archive/0.25.2.tar.gz
    fn: 0.25.2.tar.gz

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas
    - numpy >=1.14
    - scipy
    - openmm >=7.3
    - mdtraj >=1.7.2
    - openmmtools >=0.19.0
    - pymbar
    - docopt
    - openmoltools >=0.7.5
    - mpiplus
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus
    - matplotlib
    - jupyter
    - pdbfixer

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT
  license_file: LICENSE
