package:
  name: yank
  version: 0.6.2

source:
    git_url: https://github.com/choderalab/yank.git
    git_tag: 0.6.2

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt
    - openmoltools
    - jinja2

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt
    - openmoltools
    - mpi4py
    - pyyaml
    - jinja2
    - clusterutils

test:
  requires:
    - nose
  imports:
    - yank
  commands:
    - nosetests yank --nocapture --verbosity=2 --with-doctest -a '!slow'
    - which yank
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: GPU-accelerated calculation of ligand binding affinities in implicit and explicit solvent using alchemical free energy methodologies