package:
  name: yank
  version: "0.15.0"

source:
    git_url: https://github.com/choderalab/yank.git
    git_tag: "0.15.0"

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm >=7.0.1
    - mdtraj >=1.7.2
    - openmmtools
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools
    - sphinxcontrib-bibtex
    - alchemy
    - schema >=0.6.2
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm >=7.0.1
    - mdtraj >=1.7.2
    - openmmtools
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools
    - mpi4py # [not win]
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy
    - schema >=0.6.2
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: MIT License
