package:
  name: ensembler
  version: !!str 1.0.5

source:
   git_url: https://github.com/choderalab/ensembler
   git_tag: v1.0.5

build:
  number: 1
  entry_points:
    - ensembler = ensembler.cli:main
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - modeller ==9.16
    - mdtraj
    - msmbuilder
    - biopython
    - openmm
    - pdbfixer ==1.2
    # - numpy
    - lxml
    - pyyaml
    - docopt
    - mock
    - subprocess32 # [py2k]

test:
  requires:
    - nose
  imports:
    - ensembler
  commands:
    #- nosetests ensembler -v -a unit
    - ensembler init

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Pipeline for automating omics-scale protein modeling and simulation setup.
