package:
  name: rednose
  version: !!str 0.4.1

source:
  fn: rednose-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/r/rednose/rednose-0.4.1.tar.gz
  md5: 8f5705c22a7f898ded65dd7b64c1f6de
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rednose = rednose:main
    #
    # Would create an entry point called rednose that calls rednose.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-termstyle >=0.1.7

  run:
    - python
    - setuptools
    - python-termstyle >=0.1.7

test:
  # Python imports
  imports:
    - rednose

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://gfxmonk.net/dist/0install/rednose.xml
  license: BSD License
  summary: 'coloured output for nosetests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
