package:
  name: behave
  version: !!str 1.2.5

source:
  fn: behave-1.2.5.tar.gz
  url: https://pypi.python.org/packages/source/b/behave/behave-1.2.5.tar.gz
  md5: 3af4bc2886d2be982e41bfaba61da3bc

build:
  entry_points:
    - behave = behave.__main__:main

requirements:
  build:
    - python
    - setuptools
    - parse >=1.6.3
    - parse_type >=0.3.4
    - six
    - enum34 # [py27]

  run:
    - python
    - parse >=1.6.3
    - parse_type >=0.3.4
    - six
    - enum34 # [py27]

test:
  # Python imports
  imports:
    - behave
    - behave.compat
    - behave.formatter
    - behave.reporter

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - behave --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/behave/behave
  license: BSD License
  summary: 'behave is behaviour-driven development, Python style'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
