package:
  name: behave
  version: !!str 1.2.4

source:
  fn: behave-1.2.4.tar.gz
  url: https://pypi.python.org/packages/source/b/behave/behave-1.2.4.tar.gz
  md5: 13c21668c1434f67941955ffe9e12d26
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - behave = behave:main
    #
    # Would create an entry point called behave that calls behave.main()

    - behave = behave.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - parse >=1.6.3
    - parse_type >=0.3.4
    - six
    - enum34 # [not py34]

  run:
    - python
    - parse >=1.6.3
    - parse_type >=0.3.4
    - six
    - enum34 # [not py34]

test:
  # Python imports
  imports:
    - behave
    - behave.compat
    - behave.formatter
    - behave.reporter

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - behave --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/behave/behave
  license: BSD License
  summary: 'behave is behaviour-driven development, Python style'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
