package:
  name: openmm
  version: 7.0.1

source:
  git_url: https://github.com/pandegroup/openmm.git
  git_rev: 5e86c4f

build:
  number: 0
  skip: True # [win]

# by default upload binaries to 'rc' channel on anaconda.org
extra:
  upload: rc

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake     [not win]
    - jom       [win]
    - python
    # Pin fftw3f to 3.3.3 to work around OSX py34 issues
    - fftw3f ==3.3.3 [not win]
    - fftw3f ==3.3.4 [win]
    # swig is pinned to use omnia swig 3.0.7
    - swig ==3.0.7
    # on osx, need to install doxygen manually
    - doxygen   [not osx]
    # for building docs
    - sphinx
    - sphinxcontrib-bibtex
    - sphinxcontrib-lunrsearch
    - sphinxcontrib-autodoc_doxygen
    - lxml

  run:
    - python
    - fftw3f

test:
  requires:
    - python
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation
    - python -c "import simtk ; print simtk.openmm.version.git_revision"
    - python -c "from simtk import openmm ; print openmm.version.git_revision"

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
