package:
  name: openmmtools
  version: 0.0.0

source:
  url: https://github.com/choderalab/openmmtools/archive/master.zip
  fn: master.zip

requirements:
  build:
    - python
    - cython
    - numpy
    - nose
    - scipy
    - setuptools
    - openmm


  run:
    - python
    - scipy
    - openmm
    - nose

build:
  # Preserve the Python egg directory. This is needed for some packages
  # that use setuptools specific features.
  preserve_egg_dir: yes # (default no)

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

