package:
  name: openmmtools
  version: 0.18.2

source:
    fn: 0.18.2.tar.gz
    url: https://github.com/choderalab/openmmtools/archive/0.18.2.tar.gz

build:
  number: 1
  skip: True  # [py2k or win32]

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python
    - numpy >=1.14
    - scipy
    - openmm >=7.3.1
    - setuptools
    - jinja2
    - six
    - parmed
    - mdtraj
    - netcdf4 >=1.4.2 # after bugfix: "always return masked array by default, even if there are no masked values"
    - libnetcdf >=4.6.2 # workaround for libssl issues
    - sphinxcontrib-bibtex
    - mpiplus
    - cython
    - pyyaml
    - pymbar

test:
  requires:
    - nose
  imports:
    - openmmtools


about:
  home: https://github.com/choderalab/openmmtools
  license: MIT
  summary: "An OpenMM toolkit: test systems, integrators, and alchemical support"
