package:
  name: pymbar
  version: 3.0.0.beta1

source:
  url: https://github.com/choderalab/pymbar/archive/3.0.0.beta1.tar.gz
  fn: 3.0.0.beta1.tar.gz

build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - numexpr
    - six
  run:
    - python
    - numpy
    - scipy
    - numexpr
    - six

test:
  requires:
    - nose
    - setuptools
    - statsmodels
  imports:
    - pymbar
  commands:
    - nosetests pymbar --with-doctest --doctest-tests -v

about:
  home: https://github.com/choderalab/pymbar
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR) method.
