package:
  name: smirnoff99frosst
  version: "1.1.0"

source:
  git_url: https://github.com/openforcefield/smirnoff99frosst.git
  git_tag: 1.1.0


build:
  preserve_egg_dir: True
  number: 2 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]
  entry_points:
    - smirnoff99frosst = smirnoff99frosst.smirnoff99frosst:main
  noarch: python
  script: 
    - ${PYTHON}  -m pip install .

extra:
 upload: main
# include_omnia_label: rc

about:
  home: https://github.com/openforcefield/smirnoff99frosst
  license: CC-BY
  summary: 'The smirnoff99Frosst line of force fields'

requirements:
  build:
    - python
    - cython
    - setuptools
  run:
    - python
    - cython
    - setuptools
