package:
  name: algopy
  version: "0.5.1"

source:
  fn: algopy-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/a/algopy/algopy-0.5.1.tar.gz
  md5: 8aad87cb8c54d114e4f5c851f875a63b
  # number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - algopy
    - algopy.linalg
    - algopy.nthderiv
    - algopy.special
    - algopy.tests
    - algopy.tracer
    - algopy.tracer.tests
    - algopy.tracer.tests.test_output
    - algopy.utpm
    - algopy.utpm.tests

about:
  home: http://packages.python.org/algopy
  license: BSD
  summary: 'ALGOPY: Taylor Arithmetic Computation and Algorithmic Differentiation'
