package:
  name: openblas
  version: "0.2.14"

source:
  fn: openblas-0.2.14.tgz
  url: http://github.com/xianyi/OpenBLAS/tarball/v0.2.14
  md5: d340dc3d8a03f549ae29488d737b9c30

build:
  skip:
    - [not win]

requirements:
  build:
    - mingwpy

about:
  home:
  license:
  summary:
