package:
  name: openmm-example-plugin
  version: "0.0.1"


source:
  git_url: https://github.com/peastman/openmmexampleplugin.git
  git_rev: f1e12743d7c5403bb6d7ad8da69af6a2f27e1b26

build:
  skip: True  # [win]

requirements:
  build:
    - openmm
    # on windows, need to install cmake manually
    - cmake     [not win]
    - jom       [win]
    - python
    # swig is pinned to use omnia swig 3.0.8
    - swig ==3.0.8

  run:
    - python
    - openmm

test:
  requires:
    - openmm
    - python
  imports:
    - exampleplugin

about:
  home: https://github.com/peastman/openmmexampleplugin
  summary: An example plugin for openmm
