package:
  name: openmm-example-plugin
  version: "0.0.1"


source:
  git_url: https://github.com/peastman/openmmexampleplugin.git
  git_rev: f1e12743d7c5403bb6d7ad8da69af6a2f27e1b26

build:
  skip: True  # [win]
    
requirements:
  build:
    - openmm
    - cmake
    - python
    - swig ==3.0.7

  run:
    - python
    - openmm

test:
  requires:
    - python
    - openmm
  imports:
    - exampleplugin

about:
  home: https://github.com/peastman/openmmexampleplugin
  summary: An example plugin for openmm
