package:
  name: openpathsampling
  version: 0.9.2

source:
  git_url: https://github.com/openpathsampling/openpathsampling.git
  git_tag: v0.9.2

build:
  preserve_egg_dir: True
  number: 0
  skip: True  # [win and py27]

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - pyyaml
    - mdtraj
    - svgwrite
    - networkx
    - pyqt 4.11.4 py27_3
    - matplotlib
    - ujson

#test:
  #imports:
    #- openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
