package:
  name: freeglut
  version: 3.0.0

source:
  fn: freeglut-3.0.0.tar.gz
  url: http://sourceforge.net/projects/freeglut/files/freeglut/3.0.0/freeglut-3.0.0.tar.gz

build:
  number: 1
  skip:
    - [osx or win]

requirements:
    build:
      - cmake
#        - freeglut
#     - perl
#     - gcc
#        - libxml2
#        - numpy
#        - python
#    run:
#        - python
#        - numpy

# TODO: test eg. linkage against glew
#test:

about:
    home: http://opencv.org/
    license: BSD
