package:
  name: ensembler
  version: !!str 1.0.3

source:
   git_url: https://github.com/choderalab/ensembler
   git_tag: v1.0.3

build:
  entry_points:
    - ensembler = ensembler.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - modeller
    - mdtraj
    - msmbuilder
    - biopython
    - openmm
    - pdbfixer
    # - numpy
    - lxml
    - pyyaml
    - docopt
    - mock
    - subprocess32 # [py2k]

test:
  requires:
    - nose
  imports:
    - ensembler
  commands:
    - nosetests ensembler -v -a unit

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Pipeline for automating omics-scale protein modeling and simulation setup.
