package:
  name: autoprotocol
  version: "3.5.2"

source:
  fn: autoprotocol-3.5.2.tar.gz
  url: https://pypi.python.org/packages/3c/aa/6835e5833c142ee654b33f63e119f701fe8e0e1936d61a9dc03f017b63b8/autoprotocol-3.5.2.tar.gz
  md5: 8405d7c17487a7340ae0448b36c29a77
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - autoprotocol = autoprotocol:main
    #
    # Would create an entry point called autoprotocol that calls autoprotocol.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pint >=0.7.2

  run:
    - python
    - pint >=0.7.2

test:
  # Python imports
  imports:
    - autoprotocol

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/autoprotocol/autoprotocol-python
  license: BSD
  summary: 'Python library for generating Autoprotocol'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
