{% set version = "1.2.7" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  fn: netCDF4-{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf4-python/archive/v{{ version }}rel.tar.gz
  sha256: 42255f15341ae1959f814443385af4be5ae012b42e2202f300a5e5095338f54e

build:
  number: 0
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
  run:
    - python
    - setuptools
    - numpy x.x
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*

test:
  imports:
    - netCDF4
    - netcdftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h
    - conda inspect linkages -p $PREFIX netcdf4  # [not win]
    - conda inspect objects -p $PREFIX netcdf4  # [osx]

about:
  home: http://github.com/Unidata/netcdf4-python
  license: OSI Approved and MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library.'
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  omnia-md-recipe-maintainer:
    - lnaden # Note: Not author of the recipe or source code
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
  copyright:
    - This is a copy of the conda-forge meta.yaml file. This package can be removed when we move to conda-forge