package:
  name: yank-examples
  version: "0.0.0"

source:
    git_url: https://github.com/choderalab/yank-examples.git
    git_tag: "0.0.0"

build:
  number: 0
  skip:
    - [win]
requirements:
  build:
    - yank >=0.12.0
    - ambermini 16.16.0 6

  run:
    - yank >=0.12.0
    - ambermini 16.16.0 6

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank

about:
  home: https://github.com/choderalab/yank-examples
  license: MIT License
