package:
  name: msmtools 
  version: !!str 1.0

source:
  fn: v1.0.zip
  url: https://github.com/markovmodel/msmtools/archive/v1.0.zip 

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy >=1.7
    - scipy 
    - nose

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy

test:
  imports:
    - msmtools 

about:
  home: http://emma-project.org
  license: BSD 2-Clause License
  summary: "MSMTools"
