package:
  name: silo
  version: 4.10.2

source:
  url: https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2-bsd-smalltest.tar.gz
  fn: silo-4.10.2-bsd-smalltest.tar.gz

build:
  number: 0
  # 2017-01-08 "coverage" not available for py36
  skip: True  # [win or py36]

requirements:
  build:
    - hdf5
    - zlib
  run:
    - hdf5
    - zlib

about:
  license: BSD
  summary: Silo is a library for reading and writing a wide variety of scientific data to binary, disk files.
  home: https://wci.llnl.gov/simulation/computer-codes/silo
