package:
  name: protons
  version: 0.0.1a2

source:
    url: https://github.com/choderalab/protons/archive/0.0.1a2.tar.gz
    fn: 0.0.1a2.tar.gz

build:
  number: 0
  skip: True # fix later

requirements:
  build:
    - python
    - openmm >=7.2
    - numpy >=1.14
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - openmoltools >=0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - joblib
    - lxml
    - parmed <=2.7.3 # Pinned due to bug
    - pytest
    - pytest-runner
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - beautifulsoup4 # for deserialization of html tables
    - saltswap >=0.5.2 # for counterion coupling
    - networkx # matching protonation state structures

  run:
    - python
    - openmm >=7.2
    - numpy >=1.14
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - openmoltools >=0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - joblib
    - lxml
    - parmed <=2.7.3 # Pinned due to bug
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - saltswap >=0.5.2 # for counterion coupling
    - beautifulsoup4 # for deserialization of html tables
    - networkx # matching protonation state structures

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - behave

  imports:
    - protons

about:
  home: https://github.com/choderalab/protons
  license: MIT
