package:
  name: cvxcanon
  version: "0.0.23.4"

source:
  fn: CVXcanon-0.0.23.4.tar.gz
  url: https://pypi.python.org/packages/1c/ea/879ffaa990a4a769063005c02ecdc2881945da7325837cd315da8acf8f4c/CVXcanon-0.0.23.4.tar.gz
  md5: f8f80f63cb9ab8f862fcb79a12507954

requirements:
  build:
    - python
    - numpy x.x
    - scipy

  run:
    - python
    - numpy x.x
    - scipy

test:
  imports:
    - CVXcanon

about:
  home: https://github.com/cvxgrp/CVXcanon
  license: GPLv3
  summary: 'A low-level library to perform the matrix building step in cvxpy, a convex optimization modeling software.'


