package:
    name: pygraphviz
    version: 1.4rc1
source:
    fn: pygraphviz-1.4rc1.tar.gz
    md5: 2f950fb2a61a2dc85efc89543523ec07
    url: https://pypi.io/packages/source/p/pygraphviz/pygraphviz-1.4rc1.tar.gz
build:
    number: '0'
requirements:
    build:
        - python
        - graphviz
        - setuptools
        - toolchain
    run:
        - python
        - graphviz
test:
    imports:
        - pygraphviz
about:
    description: 'PyGraphviz is a Python interface to the Graphviz graph layout and

        visualization package. With PyGraphviz you can create, edit, read, write,

        and draw graphs using Python to access the Graphviz graph data structure

        and layout algorithms. PyGraphviz provides a similar programming

        interface to NetworkX (http://networkx.github.io).

        '
    home: http://pygraphviz.github.io
    license: BSD
    summary: PyGraphviz is a Python interface to the Graphviz graph layout
