package:
  name: schema
  version: !!str 0.6.2

source:
  fn: schema-0.6.2.tar.gz
  url: https://pypi.python.org/packages/9b/3c/5924163d693f156684e1502df0b408512e18c70d7fa80244496fafdb5988/schema-0.6.2.tar.gz
  mdf: ac1b359c31e9b37fbe9333902f6bdf76

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - schema

about:
  home: http://github.com/halst/schema
  license: MIT License
  summary: 'Simple data validation library'
