package:
  name: ecos
  version: !!str 1.0.5

source:
  fn: ecos-1.0.5.tar.gz
  url: https://pypi.python.org/packages/source/e/ecos/ecos-1.0.5.tar.gz
  md5: e62685b2a9aa50e519162f1373d8f001
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ecos = ecos:main
    #
    # Would create an entry point called ecos that calls ecos.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

test:
  # Python imports
  imports:
    - ecos

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/embotech/ecos
  license: GPLv3
  summary: 'This is the Python package for ECOS: Embedded Cone Solver. See Github page for more information.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
