package:
  name: oset
  version: !!str 0.1.3

source:
  fn: oset-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/o/oset/oset-0.1.3.tar.gz
  md5: f23e5a545d2c77df3916398d2d39a3ab

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - oset

about:
  home: https://gitorious.com/sleipnir/python-oset
  license:  Python Software Foundation License
  summary: 'Ordered Set.'
