package:
  name: pint
  version: !!str 0.6

source:
  fn: Pint-0.6.zip 
  url: https://pypi.python.org/packages/source/P/Pint/Pint-0.6.zip 
  md5: 88aa0918019071546b10c5fbdc91ae5e 

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docopt = docopt:main
    #
    # Would create an entry point called docopt that calls docopt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pint

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pint.readthedocs.org/en/0.6/ 
  license:  BSD License
  summary: 'Physical quantities module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
