package:
  name: boost
  version: 1.58.0

source:
   url: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2
   fn: boost_1_58_0.tar.bz2
   patches:
     # Bug in boost 1.58.0 for python 3.0, 3.1, 3.2, 3.3
     # http://lists.boost.org/Archives/boost/2015/04/221614.php
     - 3e405b6fd5db5615bbef241763de070118222ca7.patch

build:
  number: 0

requirements:
  build:
    - python
    - bzip2
    - zlib

  run:
    # this includes boost.python which is linked against libpython.
    # so we need to make sure we create a different conda binary to
    # go along with different versions of python.
    - python
    - bzip2
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

   
