package:
  name: ipynbtest
  version: "0.2.0"

build:
  preserve_egg_dir: True
  number: 0

source:
  url: https://github.com/jhprinz/ipynb-test/archive/b34737d7274279379bc5a752249962a819b6acdf.zip
  fn: master.zip

requirements:
  build:
    - python
    - setuptools
    - docopt
    - jinja2

  run:
    - python
    - jupyter
    - jupyter_client
    - nbformat

test:
  requires:
    - matplotlib
  files:
    - ../../examples/ipynbtest_tutorial.ipynb

about:
  home: https://github.com/jhprinz/ipynb-test
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
