package:
  name: msmb_data
  version: "1.1.0"

source:
  git_url: https://github.com/msmbuilder/msmb_data.git
  git_tag: v1.1

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x

  run:
    - python
    - six
    - numpy x.x
    - scipy

test:
  imports:
    - msmb_data

about:
  home: https://github.com/msmbuilder/msmb_data
  license: LGPLv2.1+
  summary: 'Testing data for MSMBuilder'
