package:
  name: perses
  version: 0.5.0
source:
  git_url: https://github.com/choderalab/perses.git
  git_tag: 0.5.0
build:
  preserve_egg_dir: True
  number: 2
  skip: True  # [win or py2k]
requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14
  run:
    - python
    - setuptools
    - ambertools >=19.11
    - numpy <1.18.1
    - scipy
    - pymbar
    - openmm >=7.3.1
    - openmoltools >=0.8.4
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - yank
    - progressbar2
    - tqdm
    - dask-jobqueue
    - openmmforcefields
    - openeye-toolkits
test:
  requires:
    - nose
    - nose-timer
  imports:
    - perses
about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_file: LICENSE
  summary: Experiments with expanded ensemble simulation to explore chemical and mutational space
