package:
  name: pyvisfile
  version: 2014.1

source:
  url: https://pypi.python.org/packages/source/p/pyvisfile/pyvisfile-2014.1.tar.gz#md5=4504b617356545da87ede00ef4337192
  fn: pyvisfile-2014.1.tar.gz
  md5: 4504b617356545da87ede00ef4337192
  patches:
    - setup.py.patch
    - aksetup_helper.py.patch

build:
  number: 1

requirements:
  build:
    - pyublas
    - numpy
    - python
    - pytools
    - silo

  run:
    - pyublas
    - python
    - numpy
    - pytools
    - silo

test:
  imports:
    - pyvisfile
    - pyvisfile.silo
    - pyvisfile.vtk

about:
  home: http://mathema.tician.de/software/pyvisfile/
  license: MIT
  summary: Large-scale Visualization Data Storage