package:
  name: pytest
  version: "3.0.2"

source:
  fn: pytest-3.0.2.tar.gz
  url: https://pypi.python.org/packages/2b/05/e20806c99afaff43331f5fd8770bb346145303882f98ef3275fa1dd66f6d/pytest-3.0.2.tar.gz
  md5: 61dc36e65a6f6c11c53b1388e043a9f5

build:
  noarch_python: True
  entry_points:
    - pytest=pytest:main
    - py.test=pytest:main

  number: 0

requirements:
  build:
    - python
    - setuptools
    - py >=1.4.29

  run:
    - python
    - py >=1.4.29

test:
  # Python imports
  imports:
    - _pytest
    - _pytest._code
    - _pytest.assertion
    - _pytest.vendored_packages

  commands:
    - pytest --help
    - py.test --help

about:
  home: http://pytest.org
  license: MIT License
  summary: 'pytest: simple powerful testing with Python'
  license_family: MIT

