package:
  name: bhmm
  version: "0.6"

source:
  url: https://github.com/bhmm/bhmm/archive/0.6.tar.gz
  fn: 0.6.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - scipy
    - msmtools
    - six

  run:
    - python
    - cython
    - numpy x.x
    - scipy
    - msmtools
    - six

test:
  requires:
    - nose
  imports:
    - bhmm
  commands:
    - nosetests bhmm --nocapture --verbosity=2 --with-doctest

about:
  home: https://github.com/choderalab/bhmm
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: Bayesian hidden Markov models for analysis of single-molecule trajectory data

