package:
  name: bhmm
  version: !!str 0.2.0

source:
    git_url: https://github.com/choderalab/bhmm.git
    git_tag: 0.2.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pyemma >=1.2
    - scikit-learn
    # - matplotlib
    # - seaborn

  run:
    - python
    - cython
    - numpy
    - scipy
    - pyemma >=1.2
    - scikit-learn
    # - matplotlib
    # - seaborn

test:
  requires:
    - nose
  imports:
    - bhmm
  commands:
    - nosetests bhmm --nocapture --verbosity=2 --with-doctest

about:
  home: https://github.com/choderalab/bhmm
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: Bayesian hidden Markov models for analysis of single-molecule trajectory data




