package:
  name: bhmm
  version: !!str 0.5.0

source:
  git_url: https://github.com/bhmm/bhmm.git
  git_tag: 0.5.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - msmtools
    - six

  run:
    - python
    - cython
    - numpy
    - scipy
    - msmtools
    - six

test:
  requires:
    - nose
  imports:
    - bhmm
  commands:
    - nosetests bhmm --nocapture --verbosity=2 --with-doctest

test:
  requires:
    - nose
  imports:
    - bhmm
  commands:
    - nosetests bhmm --nocapture --verbosity=2 --with-doctest

about:
  home: https://github.com/choderalab/bhmm
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: Bayesian hidden Markov models for analysis of single-molecule trajectory data




