package:
  name: sphinxcontrib-bibtex
  version: !!str 0.3.2

source:
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-bibtex/sphinxcontrib-bibtex-0.3.2.tar.gz
  fn: sphinxcontrib-bibtex-0.3.2.tar.gz
  md5: 6de8d82ea407abf1aebeb202255125ac

requirements:
  build:
    - setuptools
    - sphinx
    - python
    - oset
    - six
    - pybtex-docutils
    - latexcodec

  run:
    - python
    - sphinx
    - oset
    - six
    - pybtex-docutils
    - latexcodec

about:
  home: https://pypi.python.org/pypi/sphinxcontrib-bibtex
  license: BSD
  summary: A Sphinx extension for BibTeX style citations.
