package:
  name: jpype1
  version: !!str 0.6.0

source:
  fn: JPype1-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/J/JPype1/JPype1-0.6.0.tar.gz
  md5: f0cbbe1d0c4b563f7e435d2bffc31736

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - jpype

about:
  home: https://github.com/originell/jpype/
  license: 'Apache Software License'
  summary: 'A Python to Java bridge.'
