package:
  name: rdkit
  version: 2015.09.1

source:
  url: https://github.com/rdkit/rdkit/archive/Release_2015_09_1.tar.gz
  fn:  Release_2015_09_1.tar.gz
  md5: 622f1dd6618cf87cb8003765f90cea8c
  patches:
    - rdpaths.patch
    - rdconfig.patch [win]

build:
  number: 1
  skip:
    - [win]

requirements:
  build:
    - cmake [unix]
    - requests
    - boost
    - python
    - numpy
    - pillow
    - freetype
    - py2cairo [linux and py2k]
  run:
    - python
    - numpy
    - boost [linux]

test:
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Dbase
    - rdkit.ML
    - rdkit.RDPaths
    - rdkit.VLib
    - rdkit.Chem
    - rdkit.DistanceGeometry
    - rdkit.Numerics
    - rdkit.RDRandom
    - rdkit.DataManip
    - rdkit.ForceField
    - rdkit.RDConfig
    - rdkit.DataStructs
    - rdkit.Geometry

about:
  home: http://rdkit.org
  license: BSD
  summary: "Open-Source Cheminformatics Software"
