package:
  name: cvxpy
  version: "0.4.0"

source:
  fn: cvxpy-0.4.0.tar.gz
  url: https://pypi.python.org/packages/4a/10/79fd9e9b5cdd89abca9a89a9ba6c42292ced92976afce7a5de64102f16fd/cvxpy-0.4.0.tar.gz#md5=e7b0ce47b35a3f085fd440f88e9cab5a
  md5: e7b0ce47b35a3f085fd440f88e9cab5a

build:
  skip:
    # TODO no cvxopt on win py35
    - [win and py35]
    # some win-64 bug in cvxpy reported here:
    # https://github.com/cvxgrp/cvxpy/issues/236
    - [win64]

requirements:
  build:
    - python
    - setuptools
    - cvxopt
    - ecos
    - scs
    - six
    - toolz
    - numpy
    - scipy
    - cvxcanon
    - multiprocess

  run:
    - python
    - cvxopt
    - ecos
    - scs
    - six
    - toolz
    - numpy
    - scipy
    - cvxcanon
    - multiprocess

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.cvxopt_interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.tests
    - cvxpy.utilities

  commands:
    - nosetests cvxpy

  requires:
    - nose

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
