package:
  name: cvxpy
  version: !!str 0.3.1

source:
  fn: cvxpy-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxpy/cvxpy-0.3.1.tar.gz
  md5: 5d4c2a6862bbdd1cefb234786696900a

build:
  # TODO: no cvxopt on win py35 and win64 bug (https://github.com/cvxgrp/cvxpy/issues/236)
  skip: True  # [(win and py35) or win64]

requirements:
  build:
    - python
    - setuptools
    - cvxopt
    - ecos
    - scs
    - toolz
    - numpy
    - scipy
    - cvxcanon

  run:
    - python
    - cvxopt
    - ecos
    - scs
    - toolz
    - numpy
    - scipy
    - cvxcanon

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.cvxopt_interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.tests
    - cvxpy.utilities


about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
