package:
  name: pytram
  version: "0.3.0"

source:
  fn: pytram-0.3.0.tar.gz
  url: https://github.com/markovmodel/pytram/archive/0.3.0.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  skip:
    - [py3k]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython >=0.15

  run:
    - python
    - numpy x.x

test:
  # Python imports
  imports:
    - pytram
    - pytram._dtram
    - pytram._xtram

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: https://github.com/markovmodel/pytram
  license: BSD License
  summary: 'The TRAM package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
