{% set version = "2.3" %}

package:
  name: pyemma
  version: {{ version }}
source:
  fn: pyEMMA-{{ version }}.tar.gz
  url: https://github.com/markovmodel/PyEMMA/archive/v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython

    - mdtraj >=1.8
    - numpy x.x
    - scipy

  run:
    - python
    - setuptools
    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.8 
    - mock
    - funcsigs
    - msmtools >=1.2
    - thermotools >=0.2.3
    - numpy x.x
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0
    - progress_reporter >=1.3.1

#test:
#  imports:
#    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: 'PyEMMA (EMMA = Emmas Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations'
  description: |
    PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)

