package:
  name: pyemma
  version: 2.1.2
source:
  fn: pyEMMA-2.1.2.tar.gz
  url: https://github.com/markovmodel/PyEMMA/archive/v2.1.2.tar.gz

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20

    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
# this ugly workaround reflects the fact, that pytables is not available
# on py35, np19 for platform win32, so fallback to older version of mdtraj
    - mdtraj >=1.6 # [ not (py35 and win32)]
    - mdtraj >=1.5 # [(py35 and win32)]
    - mock
    - msmtools
    - thermotools >=0.1.14
    - nose
    - numpy x.x
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0

  run:
    - python
    - setuptools
    - bhmm >=0.6,<0.7
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.6 # [ not (py35 and win32)]
    - mdtraj >=1.5 # [(py35 and win32)]
    - mock
    - msmtools
    - thermotools >=0.1.14
    - numpy x.x
    - pyyaml
    - scipy
    - six
    - psutil >=3.1.1
    - decorator >=4.0.0

test:
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"

