package:
  name: pyemma
  version: !!str 1.2

source:
  fn: pyEMMA-1.2.zip
  url: https://pypi.python.org/packages/source/p/pyEMMA/pyEMMA-1.2.zip#md5=eca9a5ab6807e7c10d642af3beba33bc
  sha256: 289fe02eb482ded3474c94d6a46177389fb2b501a4b4fd734c441384778fed46
#  git_url: https://github.com/markovmodel/PyEMMA.git
#  git_tag: v1.2

build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
# mdtraj depends at least on np18, which will then enforce to use scipy>=0.14
    - numpy >=1.7
    - scipy 
# sklearn will be obsolete in 1.3
    - scikit-learn
    - mdtraj
    - matplotlib

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy
    - scikit-learn
    - mdtraj
    - matplotlib

test:
  requires:
    - nose
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: BSD 2-Clause License
  summary: "EMMA: Emma's Markov Model Algorithms"


