package:
  name: pyemma
  version: !!str 1.0a1-19-g983f910

source:
  fn: pyEMMA-v1.0a1-19-g983f910.tar.gz
  url: https://pypi.python.org/packages/source/p/pyEMMA/pyEMMA-v1.0a1-19-g983f910.tar.gz
  md5: f299d8ab8a8f94035ca64da1df218d11

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3

  run:
    - python
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3

test:
  imports:
    - pyemma
about:
  home: http://github.com/markovmodel/PyEMMA
  license:  BSD License
  summary: "EMMA: Emma's Markov Model Algorithms"


