package:
  name: pyemma
  version: !!str 1.2.2

source:
  fn: pyEMMA-1.2.2.tar.gz
  url: https://github.com/markovmodel/PyEMMA/archive/v1.2.2.tar.gz

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy >=1.7
    - scipy 
    - mdtraj
    - matplotlib
    - nose
    - mock

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy
    - mdtraj
    - matplotlib

test:
  requires:
    - nose
  imports:
    - pyemma
#  commands:
#    - nosetests pyemma --verbose

about:
  home: http://emma-project.org
  license: BSD 2-Clause License
  summary: "EMMA: Emma's Markov Model Algorithms"


