package:
  name: pyemma
  version: 2.0.2
source:
  fn: pyEMMA-2.0.2.tar.gz
  url: https://github.com/markovmodel/PyEMMA/archive/v2.0.2.tar.gz

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20

    - bhmm ==0.5.2
    - joblib
    - matplotlib
    - mdtraj
    - nose # actually this should not be here...
    - mock
    - msmtools
    - numpy >=1.7
    - scipy
    - six
    - psutil
    - decorator

  run:
    - python
    - setuptools
    - bhmm ==0.5.2
    - joblib
    - matplotlib
    - mdtraj
    - mock
    - msmtools
    - numpy >=1.7
    - scipy
    - six
    - psutil
    - decorator


test:
  imports:
    - pyemma

about:
  home: http://emma-project.org
  license: GNU Lesser Public License v3+
  summary: "EMMA: Emma's Markov Model Algorithms"

