package:
  name: pyemma
  version: !!str 1.0a2

source:
  fn: pyEMMA-v1.0a2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyEMMA/pyEMMA-1.0a2.tar.gz
  md5: 54133cbf879ad7875ea5bc461ec71f00 

requirements:
  build:
    - python
    - setuptools
    - cython >=0.20
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3

  run:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3

test:
  imports:
    - pyemma
about:
  home: http://github.com/markovmodel/PyEMMA
  license:  BSD License
  summary: "EMMA: Emma's Markov Model Algorithms"


