{% set conda_name = "pyemma" %}
{% set name = "pyEMMA" %} 
{% set version = "2.3.2" %}
{% set sha256 = "7399378652217459a068ce7d20811d3c9ff65154bb5e869e30171cc86c7fdd02" %}

package:
  name: {{ conda_name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    - mdtraj >=1.8
    - numpy x.x
    - python
    - setuptools

  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.8
    - mock
    - msmtools >=1.2
    - numpy x.x
    - progress_reporter >=1.3.1
    - psutil >=5
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.1.0
    - thermotools >=0.2.5

test:
  imports:
    - pyemma

about:
  home: http://github.com/markovmodel/pyemma
  license: LGPLv3+ 
  license_file: LICENSE.txt
  summary: "PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations"

  description: |
    PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)
  doc_url: http://emma-project.org
  dev_url: https://github.com/markovmodel/pyemma

extra:
  recipe-maintainers:
    - franknoe
    - marscher
