package:
  name: mdtraj
  version: "1.5.0"

source:
  fn: mdtraj-1.4.2.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.5.0.tar.gz#md5=d30b9859daf8dc2f8273cc6679c73eff
  md5: d30b9859daf8dc2f8273cc6679c73eff

build:
  number: 1
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - scripttest

  run:
    - python
    - numpy x.x
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
