package:
  name: mdtraj
  version: "1.8.0"

source:
  fn: mdtraj-1.8.0.tar.gz
  url: https://pypi.python.org/packages/cd/9f/027fa58d4e93dd3d700e22d5766961c970f6882c2bffd33daef55219d078/mdtraj-1.8.0.tar.gz#md5=b350f3ce5deba70d824e9420ae53b00a
  md5: b350f3ce5deba70d824e9420ae53b00a
  patches:
    # Necessary for building 1.8.0, should be fixed by next version
    - 1208-find-zlib.patch
    - declare_init_order.patch
    - math.patch #  [py27 and win]

build:
  number: 1
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - zlib 1.2.*

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - pytables
    
test:
  imports:
    - mdtraj
  commands:
    - mdconvert -h

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
