package:
  name: openforcefields
  version: "2.0.0rc.2"

source:
  git_url: https://github.com/openforcefield/openforcefields.git
  git_tag: 2.0.0-rc.2

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]
  entry_points:
    - openforcefields = openforcefields.openforcefields:main
  noarch: python
  script: 
    - ${PYTHON}  -m pip install .

extra:
 upload: main
 # include_omnia_label: rc

about:
  home: https://github.com/openforcefield/openforcefields
  license: CC-BY
  summary: 'Force fields released by the Open Force Field Initiative'

requirements:
  build:
    - python
    - cython
    - setuptools
  run:
    - python
    - cython
    - setuptools
