package:
  name: python-coveralls
  version: !!str 2.5.0

source:
  fn: python-coveralls-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-coveralls/python-coveralls-2.5.0.tar.gz
  md5: e66878a926b9d5dd04250e1a05080fbd
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-coveralls = python-coveralls:main
    #
    # Would create an entry point called python-coveralls that calls python-coveralls.main()

    - coveralls = coveralls:wear

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - requests
    - coverage ==3.7.1
    - six
    - sh

  run:
    - python
    - pyyaml
    - requests
    - coverage ==3.7.1
    - six
    - sh

test:
  # Python imports
  imports:
    - coveralls

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - coveralls --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache Software License
  summary: 'Python interface to coveralls.io API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
