package:
  name: python-coveralls
  version: !!str 2.5.0

source:
  fn: python-coveralls-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-coveralls/python-coveralls-2.5.0.tar.gz
  md5: e66878a926b9d5dd04250e1a05080fbd

build:
  entry_points:
    - coveralls = coveralls:wear
  # 2018-01-08 coverage missing for py36
  skip: True  # [win or py36]

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - requests
    - coverage ==3.7.1
    - six
    - sh

  run:
    - python
    - pyyaml
    - requests
    - coverage ==3.7.1
    - six
    - sh

test:
  # Python imports
  imports:
    - coveralls

  commands:
    - coveralls --help

about:
  home: http://github.com/z4r/python-coveralls
  license: Apache Software License
  summary: 'Python interface to coveralls.io API'
