package:
  name: msmbuilder
  version: !!str 2.8.1

source:
  fn: msmbuilder-2.8.1.tar.gz
  url: https://pypi.python.org/packages/source/m/msmbuilder/msmbuilder-2.8.1.tar.gz

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - msmbuilder = msmbuilder:main
    #
    # Would create an entry point called msmbuilder that calls msmbuilder.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj

  run:
    - python
    - numpy
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj

test:
  # Python imports
  imports:
    - msmbuilder.project
    - msmbuilder
    - msmbuilder.scripts
    - msmbuilder.lumping
    - msmbuilder.metrics
    - msmbuilder.reduce
    - msmbuilder.geometry

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://msmbuilder.org
  license: GPLv3.0
  summary: 'MSMBuilder: a python library for Markov state models of conformational dynamics'

