package:
  name: sphinxcontrib-autodoc_doxygen
  version: "0.3.1"

source:
  fn: sphinxcontrib-autodoc_doxygen-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-autodoc_doxygen/sphinxcontrib-autodoc_doxygen-0.3.1.tar.gz
  md5: fcfbc77a810900865b143b7aa9409e2f

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - setuptools
    - python
    - sphinx >=1.3.1
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - mock
    - pbr

  run:
    - python
    - sphinx >=1.3.1
    - docutils >=0.11
    - jinja2 >=2.3
    - lxml
    - mock

about:
  home: https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen
  license: MIT License
  summary: 'Doxygen / Sphinx bridge, with autodoc and autosummary'
