package:
  name: ambermini
  version: 15.0.3

source:
  fn: 15.0.3.zip
  url: https://github.com/choderalab/ambermini/archive/15.0.3.zip
  md5: fcaf6410c5012460a99ad8f6ac5e35cd

build:
  number: 0

requirements:
  build:
    - zlib
  run:
    - zlib

test:
  commands:
    - antechamber -h
    - sqm -h
    - tleap -h

about:
  home: https://github.com/choderalab/ambermini/
  license: LGPL
  summary: A stripped-down version of AmberTools 14 containing antechamber, sqm, tleap, and parmchk2
