package:
  name: ambermini
  version: 16.16.0

source:
  fn: 16.16.0.zip
  url: https://github.com/choderalab/ambermini/archive/16.16.0.zip

build:
  number: 6
  skip: True [win]

requirements:
  build:
    - zlib
    - flex     [unix]
    - bison    [unix]
    - gcc  [unix]
    - mingwpy  [win]

  run:
    - zlib
    - libgcc  [unix]

test:
  commands:
    - antechamber -h
    - sqm -h
    - tleap -h

about:
  home: https://github.com/choderalab/ambermini/
  license: LGPL
  summary: A stripped-down version of AmberTools 16 containing antechamber, sqm, tleap, parmchk2, and paramfit
