package:
  name: ambermini
  version: 15.0.0

source:
  fn: 15.0.0.zip
  url: https://github.com/choderalab/ambermini/archive/15.0.0.zip
  md5: 0824c83bb4c35cfaca81cb406c370197

build:
  number: 0

requirements:
  build:
    - zlib
  run:
    - zlib

test:
  commands:
    - antechamber -h
    - sqm -h
    - tleap -h

about:
  home: https://github.com/choderalab/ambermini/
  license: LGPL
  summary: A stripped-down version of AmberTools 14 containing antechamber, sqm, tleap, and parmchk2
