package:
  name: fastcluster
  version: !!str 1.1.13

source:
  fn: fastcluster-1.1.13.tar.gz
  url: https://pypi.python.org/packages/source/f/fastcluster/fastcluster-1.1.13.tar.gz
  md5: ca2a5f5e8ab81628c72ed2cc0e1e21c6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fastcluster = fastcluster:main
    #
    # Would create an entry point called fastcluster that calls fastcluster.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - fastcluster

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://danifold.net
  license: BSD License or GNU General Public License v2 (GPLv2)
  summary: 'Fast hierarchical clustering routines for R and Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
